### PR TITLE
Fixed the bug that gave an incomplete result

### LINKED ISSUE #69: Incomplete Result of an executed program
- [ ] Look for examples and information
- [ ] Fix issue

### PR DESCRIPTION
**Pull request by luqp**

### CODE REVIEW

File: src/main/java/org/jalasoft/moi/model/core/Executer.java [hunk 1]
```diff
@@ -29,6 +30,7 @@
  */
```
Comment (Snip-77) [inline src/main/java/org/jalasoft/moi/model/core/Executer.java:32]: I think date needs to be deleted by convention.

**Review by Snip-77 — CHANGES_REQUESTED** [review]
Please review the comment. Also, there is missing a * in line one before the copyright.

**Review by nanrehd — DISMISSED** [review]

**Review by carlosmc23 — DISMISSED** [review]

**Review by Snip-77 — APPROVED** [review]
